#!/bin/bash
#
# Start the local server for the doc site.
#
# It only serves the current doc version, ignoring the rest.
#
set -xeuo pipefail

ROOT="$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")"

(cd "$ROOT"; poetry run mkdocs serve)
