#!/bin/bash
#
# Lint all files in the repo.
#
# Just run pre-commit hooks and mypy on all files.
#
set -xeuo pipefail

ROOT="$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")"

(cd "${ROOT}"; poetry run pre-commit run --all-files)
(cd "${ROOT}"; poetry run mypy ".")
