name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write # publishing releases

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Get full Python version
        id: full-python-version
        run: |
          echo ::set-output name=version::$(python -c "import sys; print('-'.join(str(v) for v in sys.version_info))")

      - name: Get tag name
        id: tag
        run: |
          echo "::set-output name=tag-name::${GITHUB_REF#refs/tags/}"

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.2.0
          virtualenvs-in-project: true

      - name: Set up cache for python dependencies
        uses: actions/cache@v3
        id: cache-venv
        with:
          path: .venv
          key: pydeps-release-Ubuntu-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Ensure cache is healthy
        if: steps.cache-venv.outputs.cache-hit == 'true'
        run: timeout 10s poetry run pip --version || rm -rf .venv

      - name: Install dependencies
        run: poetry install --only main --only docs --only dev -vvv

      - name: Build package
        run: poetry build

      - name: Create release and publish
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: poetry run ./scripts/publish "${{ steps.tag.outputs.tag-name }}"
